# Generated by Django 5.2.2 on 2025-06-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Fitnees_Admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("conf_password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="avaliable_classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=300)),
                ("client_email", models.EmailField(max_length=254)),
                ("slot_time", models.DateTimeField(blank=True, null=True)),
                (
                    "classes",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Fitnees_Admin.classes",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Fitnees_Admin.trainer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Fitnees.register",
                    ),
                ),
            ],
        ),
    ]
