# Generated by Django 5.2.2 on 2025-06-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                ("T_id", models.AutoField(primary_key=True, serialize=False)),
                ("T_name", models.CharField(max_length=50)),
                ("T_email", models.EmailField(max_length=254)),
                ("T_phone", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Classes",
            fields=[
                ("C_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "C_name",
                    models.CharField(
                        choices=[
                            ("Strength", "Strength"),
                            ("Yoga", "Yoga"),
                            ("HIIT", "HIIT"),
                            ("Cardio", "Cardio"),
                        ],
                        default="Cardio",
                        max_length=50,
                    ),
                ),
                ("C_description", models.TextField()),
                ("C_date", models.DateField()),
                ("C_start_time", models.TimeField()),
                ("C_end_time", models.TimeField()),
                (
                    "C_trainer",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Fitnees_Admin.trainer",
                    ),
                ),
            ],
        ),
    ]
